var _connectorStops = [
  {
    "ID": 53,
    "Name": "108TH AVE NE & NE 6TH ST",
    "Address": "580 108th Ave NE",
    "City": "BELLEVUE",
    "Latitude": 47.615197,
    "LatitudeWaypoint": null,
    "Longitude": -122.196252,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98004",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 68,
    "Name": "16TH AVE. E. & E. THOMAS ST.",
    "Address": "16th Ave E & E Thomas St",
    "City": "SEATTLE",
    "Latitude": 47.620376,
    "LatitudeWaypoint": null,
    "Longitude": -122.311398,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98112",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 69,
    "Name": "19TH AVE E & E HARRISON ST",
    "Address": "19th Ave E & E Harrison St",
    "City": "SEATTLE",
    "Latitude": 47.6218,
    "LatitudeWaypoint": null,
    "Longitude": -122.307342,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98112",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 52,
    "Name": "1ST AVE & CEDAR ST",
    "Address": "1st Ave & Cedar St",
    "City": "SEATTLE",
    "Latitude": 47.615984,
    "LatitudeWaypoint": null,
    "Longitude": -122.350761,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98121",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 66,
    "Name": "1ST AVE N & JOHN ST",
    "Address": "1st Ave N & John St",
    "City": "SEATTLE",
    "Latitude": 47.619972,
    "LatitudeWaypoint": null,
    "Longitude": -122.35543,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98109",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 72,
    "Name": "1ST AVE N. & W. HARRISON ST",
    "Address": "1st Ave N & Harrison St",
    "City": "SEATTLE",
    "Latitude": 47.62222225,
    "LatitudeWaypoint": null,
    "Longitude": -122.35538278,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98109",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 62,
    "Name": "2490 N 65th ST (PM)",
    "Address": "2490 N 65th St",
    "City": "SEATTLE",
    "Latitude": 47.675942,
    "LatitudeWaypoint": null,
    "Longitude": -122.328439,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98103",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 21,
    "Name": "24TH AVE NW & NW 67TH ST",
    "Address": "6556 24th Ave NW",
    "City": "SEATTLE",
    "Latitude": 47.677554,
    "LatitudeWaypoint": null,
    "Longitude": -122.387435,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98117",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 22,
    "Name": "24TH AVE NW & NW 77TH ST",
    "Address": "7704 24th Ave NW",
    "City": "SEATTLE",
    "Latitude": 47.685156,
    "LatitudeWaypoint": null,
    "Longitude": -122.387483,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98117",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 3,
    "Name": "2ND AVE & CEDAR ST",
    "Address": "2701 2nd Ave",
    "City": "SEATTLE",
    "Latitude": 47.616622,
    "LatitudeWaypoint": null,
    "Longitude": -122.350024,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98121",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 13,
    "Name": "35TH AVE NE & NE 73RD ST",
    "Address": "7050 35th Ave NE",
    "City": "SEATTLE",
    "Latitude": 47.681023,
    "LatitudeWaypoint": null,
    "Longitude": -122.290318,
    "LongitudeWaypoint": null,
    "StopRadius": 650,
    "Description": null,
    "ZipCode": "98115",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 14,
    "Name": "35TH AVE NE & NE 80TH ST",
    "Address": "8008 35th Ave NE",
    "City": "SEATTLE",
    "Latitude": 47.68649,
    "LatitudeWaypoint": null,
    "Longitude": -122.290487,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98115",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 11,
    "Name": "40TH AVE NE & NE 55TH ST",
    "Address": "5250 40th Ave NE",
    "City": "SEATTLE",
    "Latitude": 47.668341,
    "LatitudeWaypoint": null,
    "Longitude": -122.28472,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98105",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 12,
    "Name": "40TH AVE NE & NE 65TH ST",
    "Address": "6290 40th Ave NE",
    "City": "SEATTLE",
    "Latitude": 47.675587,
    "LatitudeWaypoint": null,
    "Longitude": -122.284795,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98115",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 61,
    "Name": "BALLARD PUBLIC LIBRARY",
    "Address": "5614 22nd Ave NW",
    "City": "SEATTLE",
    "Latitude": 47.670113,
    "LatitudeWaypoint": null,
    "Longitude": -122.384713,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98107",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 6,
    "Name": "BOTHELL STAPLES",
    "Address": "18438 120th Ave NE",
    "City": "BOTHELL",
    "Latitude": 47.76083205,
    "LatitudeWaypoint": null,
    "Longitude": -122.17577814,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98011",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 36,
    "Name": "CALIFORNIA AVE SW @ ADMIRAL THEATER",
    "Address": "2343 California Ave SW",
    "City": "SEATTLE",
    "Latitude": 47.581726,
    "LatitudeWaypoint": null,
    "Longitude": -122.386676,
    "LongitudeWaypoint": null,
    "StopRadius": 650,
    "Description": null,
    "ZipCode": "98116",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 37,
    "Name": "CALIFORNIA AVE SW AND SW HINDS ST",
    "Address": "3401 California Ave SW",
    "City": "SEATTLE",
    "Latitude": 47.574,
    "LatitudeWaypoint": null,
    "Longitude": -122.386896,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98116",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 39,
    "Name": "CEDAR PARK CRESCENT NE AND NE 100TH WAY",
    "Address": "Cedar Park Cres NE & NE 100th Way",
    "City": "REDMOND",
    "Latitude": 47.687832,
    "LatitudeWaypoint": null,
    "Longitude": -122.041605,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98053",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 35,
    "Name": "CHRISTIAN FAITH CENTER",
    "Address": "13000 21st Dr SE",
    "City": "EVERETT",
    "Latitude": 47.87887481,
    "LatitudeWaypoint": null,
    "Longitude": -122.20385643,
    "LongitudeWaypoint": null,
    "StopRadius": 1000,
    "Description": null,
    "ZipCode": "98208",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 10,
    "Name": "COMMONS TRANSPORTATION CENTER",
    "Address": "150th Ave NE",
    "City": "REDMOND",
    "Latitude": 47.64306987,
    "LatitudeWaypoint": null,
    "Longitude": -122.13992611,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98052",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": true,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 38,
    "Name": "COVINGTON CORNERSTONE CHURCH",
    "Address": "20730 SE 272nd St",
    "City": "Kent",
    "Latitude": 47.358409,
    "LatitudeWaypoint": null,
    "Longitude": -122.06376,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98042",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 58,
    "Name": "E MADISION ST & 23RD AVE (AM)",
    "Address": "E Madison St & 23rd Ave",
    "City": "SEATTLE",
    "Latitude": 47.619365,
    "LatitudeWaypoint": null,
    "Longitude": -122.302149,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98112",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 59,
    "Name": "E MADISION ST & 25TH AVE (PM)",
    "Address": "E Madison St & 25rd Ave",
    "City": "SEATTLE",
    "Latitude": 47.620834,
    "LatitudeWaypoint": null,
    "Longitude": -122.300261,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98112",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 45,
    "Name": "E MADISON ST @ CITY PEOPLE`S NURSERY (AM)",
    "Address": "2925 E Madison St",
    "City": "SEATTLE",
    "Latitude": 47.624349,
    "LatitudeWaypoint": null,
    "Longitude": -122.294792,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98112",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 44,
    "Name": "E UNION ST AND 33TH AVE (PM)",
    "Address": "E Union St & 33rd Ave",
    "City": "SEATTLE",
    "Latitude": 47.612872,
    "LatitudeWaypoint": null,
    "Longitude": -122.290495,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98122",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 43,
    "Name": "E UNION ST AND 34TH AVE (AM)",
    "Address": "E Union St & 34th Ave",
    "City": "SEATTLE",
    "Latitude": 47.613129,
    "LatitudeWaypoint": null,
    "Longitude": -122.290111,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98122",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 67,
    "Name": "E. PIKE ST. & SUMMIT AVE.",
    "Address": "E Pike St & Summit Ave",
    "City": "SEATTLE",
    "Latitude": 47.614092,
    "LatitudeWaypoint": null,
    "Longitude": -122.32567,
    "LongitudeWaypoint": null,
    "StopRadius": 700,
    "Description": null,
    "ZipCode": "98122",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 57,
    "Name": "EASTRIDGE DR NE & POWERLINES",
    "Address": "Eastridge Dr NE & Powerlines",
    "City": "REDMOND",
    "Latitude": 47.697198,
    "LatitudeWaypoint": null,
    "Longitude": -122.018875,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98053",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 33,
    "Name": "EVERGREEN STATE FAIRGROUNDS",
    "Address": "14405 179th Ave SE",
    "City": "MONROE",
    "Latitude": 47.86687254,
    "LatitudeWaypoint": null,
    "Longitude": -121.99006901,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98272",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 15,
    "Name": "GREENWOOD AVE N & N 73RD ST",
    "Address": "7307 Greenwood Ave N",
    "City": "SEATTLE",
    "Latitude": 47.682113,
    "LatitudeWaypoint": null,
    "Longitude": -122.35541,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98103",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 20,
    "Name": "GREENWOOD AVE N & N 75TH ST",
    "Address": "Greenwood Ave N & N 75th St",
    "City": "SEATTLE",
    "Latitude": 47.683497,
    "LatitudeWaypoint": null,
    "Longitude": -122.355152,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98103",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 54,
    "Name": "HIGHLANDS COMMUNITY CHURCH",
    "Address": "3031 NE 10th St",
    "City": "RENTON",
    "Latitude": 47.497344,
    "LatitudeWaypoint": null,
    "Longitude": -122.17861,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98056",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 9,
    "Name": "HOLY INNOCENTS CATHOLIC CHURCH",
    "Address": "26526 NE Cherry Valley Rd",
    "City": "DUVALL",
    "Latitude": 47.747887,
    "LatitudeWaypoint": null,
    "Longitude": -121.982896,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98019",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 64,
    "Name": "ISSAQUAH HIGHLANDS",
    "Address": "10th Ave NE",
    "City": "ISSAQUAH",
    "Latitude": 47.541288,
    "LatitudeWaypoint": null,
    "Longitude": -122.015946,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98029",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 41,
    "Name": "KENT SEVENTH DAY ADVENTIST CHURCH",
    "Address": "25213 116th Ave SE",
    "City": "KENT",
    "Latitude": 47.375639,
    "LatitudeWaypoint": null,
    "Longitude": -122.188209,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98030",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 50,
    "Name": "LAKE WASHINGTON BLVD E AND E MADISON ST (PM)",
    "Address": "Lake Washington Blvd E & E Madison St",
    "City": "SEATTLE",
    "Latitude": 47.625855,
    "LatitudeWaypoint": null,
    "Longitude": -122.29285,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98112",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 42,
    "Name": "LESCHI PARK (PARKING LOT)",
    "Address": "201 Lakeside Ave S",
    "City": "SEATTLE",
    "Latitude": 47.601114,
    "LatitudeWaypoint": null,
    "Longitude": -122.285348,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98144",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 55,
    "Name": "MARS HILL CHURCH",
    "Address": "120 228th Ave NE",
    "City": "SAMMAMISH",
    "Latitude": 47.61022841,
    "LatitudeWaypoint": null,
    "Longitude": -122.03460699,
    "LongitudeWaypoint": null,
    "StopRadius": 650,
    "Description": null,
    "ZipCode": "98074",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 5,
    "Name": "MILLCREEK FOURSQUARE CHURCH",
    "Address": "1415 164th St SW",
    "City": "LYNNWOOD",
    "Latitude": 47.85046537,
    "LatitudeWaypoint": null,
    "Longitude": -122.25343971,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98087",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 49,
    "Name": "MT RAINIER DR S AND S MCCLELLAN ST (PM)",
    "Address": "Mount Rainier Dr S & S McClellan St",
    "City": "SEATTLE",
    "Latitude": 47.577825,
    "LatitudeWaypoint": null,
    "Longitude": -122.287617,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98144",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 25,
    "Name": "N 35TH ST & WOODLAND PARK AVE N (AM)",
    "Address": "1051 N 35th AVE",
    "City": "SEATTLE",
    "Latitude": 47.649653,
    "LatitudeWaypoint": null,
    "Longitude": -122.344348,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98103",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 32,
    "Name": "N 35TH ST & WOODLAND PARK AVE N (PM)",
    "Address": "Woodland Park Ave N & N 35th St",
    "City": "SEATTLE",
    "Latitude": 47.649682,
    "LatitudeWaypoint": null,
    "Longitude": -122.343723,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98103",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 24,
    "Name": "N 36TH ST & PHINNEY AVE N",
    "Address": "401 N 36th ST",
    "City": "SEATTLE",
    "Latitude": 47.652109,
    "LatitudeWaypoint": null,
    "Longitude": -122.354074,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98103",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 28,
    "Name": "N 45TH ST & BAGLEY AVE N",
    "Address": "2115 N 45th ST",
    "City": "SEATTLE",
    "Latitude": 47.661327,
    "LatitudeWaypoint": null,
    "Longitude": -122.333,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98103",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 29,
    "Name": "N 45TH ST & MERIDIAN AVE N",
    "Address": "Meridian Ave N & N 45th St",
    "City": "SEATTLE",
    "Latitude": 47.661451,
    "LatitudeWaypoint": null,
    "Longitude": -122.333316,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98103",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 17,
    "Name": "NE 65TH ST & LATONA AVE NE - (AM)",
    "Address": "6411 Latona Ave NE",
    "City": "SEATTLE",
    "Latitude": 47.675867,
    "LatitudeWaypoint": null,
    "Longitude": -122.325645,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98115",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 18,
    "Name": "NE 65TH ST & LATONA AVE NE - (PM)",
    "Address": "NE 65th St & Latona Ave NE",
    "City": "SEATTLE",
    "Latitude": 47.675973,
    "LatitudeWaypoint": null,
    "Longitude": -122.325557,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98115",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 56,
    "Name": "NE CEDAR PARK CRESCENT & EASTRIDGE DR NE",
    "Address": "NE Cedar Park Crescent & Eastridge Dr NE",
    "City": "REDMOND",
    "Latitude": 47.691234,
    "LatitudeWaypoint": null,
    "Longitude": -122.017663,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98053",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 23,
    "Name": "OUR REDEEMERS LUTHERAN CHURCH",
    "Address": "2400 NW 85th St",
    "City": "SEATTLE",
    "Latitude": 47.691183,
    "LatitudeWaypoint": null,
    "Longitude": -122.389294,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98117",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 1,
    "Name": "OVERLAKE TRANSIT CENTER",
    "Address": "156th Ave NE & NE 40th St",
    "City": "REDMOND",
    "Latitude": 47.644307,
    "LatitudeWaypoint": null,
    "Longitude": -122.132564,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98052",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": true,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 19,
    "Name": "PHINNEY AVE N & N 55TH ST",
    "Address": "Phinney Ave N & N 55th St",
    "City": "SEATTLE",
    "Latitude": 47.668456,
    "LatitudeWaypoint": null,
    "Longitude": -122.354315,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98103",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 16,
    "Name": "PHINNEY AVE N & N ARGLE PL",
    "Address": "5555 Phinney Ave N",
    "City": "SEATTLE",
    "Latitude": 47.669303,
    "LatitudeWaypoint": null,
    "Longitude": -122.354543,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98103",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 2,
    "Name": "QUEEN ANNE AVE N & CROCKETT ST",
    "Address": "2100 Queen Anne Ave N",
    "City": "SEATTLE",
    "Latitude": 47.637203,
    "LatitudeWaypoint": null,
    "Longitude": -122.356954,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98109",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 51,
    "Name": "QUEEN ANNE AVE N & W MCGRAW ST",
    "Address": "Queen Anne Ave N & W McGraw St",
    "City": "SEATTLE",
    "Latitude": 47.639173,
    "LatitudeWaypoint": null,
    "Longitude": -122.357003,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98109",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 71,
    "Name": "QUEEN ANNE AVE N & W REPUBLICAN ST",
    "Address": "Queen Anne Ave N & W Republican St",
    "City": "SEATTLE",
    "Latitude": 47.62324843,
    "LatitudeWaypoint": null,
    "Longitude": -122.35670893,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98109",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 65,
    "Name": "QUEEN ANNE AVE N & W THOMAS ST",
    "Address": "Queen Anne Ave N & W Thomas St",
    "City": "SEATTLE",
    "Latitude": 47.62081,
    "LatitudeWaypoint": null,
    "Longitude": -122.35675,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98109",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 40,
    "Name": "REDMOND RIDGE CARPOOL LOT",
    "Address": "NE Cedar Park Cres & Redmond Ridge Trail",
    "City": "REDMOND",
    "Latitude": 47.685765,
    "LatitudeWaypoint": null,
    "Longitude": -122.033426,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98053",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 47,
    "Name": "S GENESEE ST AND 43RD AVE S (GENESEE PARK)",
    "Address": "4316 S Genesee St",
    "City": "SEATTLE",
    "Latitude": 47.563815,
    "LatitudeWaypoint": null,
    "Longitude": -122.279484,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98118",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 48,
    "Name": "S MCCLELLAN ST AND S MT BAKER BLVD (AM)",
    "Address": "3600 S McClellan St",
    "City": "SEATTLE",
    "Latitude": 47.578438,
    "LatitudeWaypoint": null,
    "Longitude": -122.288985,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98144",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 46,
    "Name": "S ORCAS ST AND 52ND AVE S (SDA CHURCH)",
    "Address": "5200 S Orcas St",
    "City": "SEATTLE",
    "Latitude": 47.551227,
    "LatitudeWaypoint": null,
    "Longitude": -122.266897,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98118",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 34,
    "Name": "SNOHOMISH HOPE FOURSQUARE CHURCH",
    "Address": "5002 Bickford Ave",
    "City": "SNOHOMISH",
    "Latitude": 47.950616,
    "LatitudeWaypoint": null,
    "Longitude": -122.118294,
    "LongitudeWaypoint": null,
    "StopRadius": 650,
    "Description": null,
    "ZipCode": "98290",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 27,
    "Name": "STONE WAY N & N 45TH ST",
    "Address": "4468 Stone Way N",
    "City": "SEATTLE",
    "Latitude": 47.661178,
    "LatitudeWaypoint": null,
    "Longitude": -122.342023,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98103",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 8,
    "Name": "TIMES SQUARE COMPLEX",
    "Address": "500 SW 39th St",
    "City": "RENTON",
    "Latitude": 47.447296,
    "LatitudeWaypoint": null,
    "Longitude": -122.224284,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98055",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 7,
    "Name": "TRAILSIDE BUILDING",
    "Address": "35161 SE Douglas St",
    "City": "SNOQUALMIE",
    "Latitude": 47.52546393,
    "LatitudeWaypoint": null,
    "Longitude": -121.87141939,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98065",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 31,
    "Name": "WALLINGFORD AVE N & 34TH ST (PM)",
    "Address": "Wallingford Ave N & N 34th St",
    "City": "SEATTLE",
    "Latitude": 47.64824,
    "LatitudeWaypoint": null,
    "Longitude": -122.336428,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98103",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 26,
    "Name": "WALLINGFORD AVE N & N 34TH ST (AM)",
    "Address": "3400 Wallingford Ave N",
    "City": "SEATTLE",
    "Latitude": 47.648235,
    "LatitudeWaypoint": null,
    "Longitude": -122.33628,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98103",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 30,
    "Name": "WALLINGFORD AVE N & N 43RD ST",
    "Address": "Wallingford Ave N & N 43rd St",
    "City": "SEATTLE",
    "Latitude": 47.658931,
    "LatitudeWaypoint": null,
    "Longitude": -122.336256,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98103",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  },
  {
    "ID": 63,
    "Name": "WEST SEATTLE CHRISTIAN CHURCH",
    "Address": "4415 41st Ave SW",
    "City": "SEATTLE",
    "Latitude": 47.56435,
    "LatitudeWaypoint": null,
    "Longitude": -122.384444,
    "LongitudeWaypoint": null,
    "StopRadius": 500,
    "Description": null,
    "ZipCode": "98116",
    "IsPick": false,
    "IsDrop": false,
    "IsHub": false,
    "DistanceFromStop": 0,
    "SecondsFromStop": 0,
    "RoutesServiced": []
  }
]